[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "manilet-praeforum"
dynamic = ["version"]
description = "백테스팅 프로그램"
readme = "README.md"
license = "MIT"
requires-python = ">=3.12"
authors = [
    { name = "agradra" }
]

dependencies = [
    "polars>=1.44.2",
    "hatchling>=1.32.3",
    "typer>=0.27.2",
    "packaging>=26.3",
]

[tool.hatch.build.targets.wheel]
packages = [
    "src/praeforum",
    "src/praeforum_app"
]
[tool.hatch.version]
source = "vcs"
fallback-version = "0.0.0.dev0"

[tool.hatch.version.raw-options]
root = ".."

[project.scripts]
praeforum = "praeforum.cli:main"


[tool.hatch.build]
# Rust 빌드
hooks.custom.enable = true
artifacts = [
    "praeforum/engine.pyd",
    "praeforum/engine.so", 
    "praeforum/gui/web_dist/**/*"
]